export const SET_FORM_VALUES = 'SET_FORM_VALUES';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_TRIVIA_QUESTIONS = 'SET_TRIVIA_QUESTIONS';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_IS_QUIZ_COMPLETED = 'SET_IS_QUIZ_COMPLETED';
export const SET_API_ERROR = 'SET_API_ERROR';
