export const SET_FORM_VALUES = 'SET_FORM_VALUES';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_TRIVIA_QUESTIONS = 'SET_TRIVIA_QUESTIONS';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
